version: "3.8"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: locadora-laravel
    # Mapeia a porta 8080 do host para a porta 80 do container
    ports:
      - "8081:80"
    # Mapeia o volume para que as alterações no código sejam refletidas no container
    volumes:
      - ./:/var/www/html
    # Define dependência do contêiner do MySQL
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: locadora-mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=locadora
      - MYSQL_USER=locadora_user
      - MYSQL_PASSWORD=secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata:
